### ISSUE TITLE
[SM] Unable to load extension "cbasenpc.ext": Failed to find signature: CTFGameRules::ApplyOnDamageModifyRules

### ISSUE THREAD

**Issue by narrs** [TF2-DMB/CBaseNPC#19]
The same error log as recorded in the title appears.
Extensions, gamedata, and plugin files are the latest and look fine.
I'm using it for Slender Fortress.
When I modified the CTFGameRules::ApplyOnDamageModifyRules in the gamedata, there will be no crash, but the boss will run strangely.

**Comment by KitRifty** [comment]
Is your SRCDS updated to the latest version? Can you post your gamedata?

**Comment by narrs** [comment]
[cbasenpc.txt](https://github.com/TF2-DMB/CBaseNPC/files/8007728/cbasenpc.txt)

**Comment by Kenzzer** [comment]
> [cbasenpc.txt](https://github.com/TF2-DMB/CBaseNPC/files/8007728/cbasenpc.txt)

This gamedata is identical (used a text comparator) to the one on the repository
[gamedata link](https://raw.githubusercontent.com/TF2-DMB/CBaseNPC/34189c5130a4b0ffe8c915fac08c63fbc74a6232/gamedata/cbasenpc.txt)
Are you sure, you did modify the gamedata. Also how did you come to the conclusion `CTFGameRules::ApplyOnDamageModifyRules` is at fault. You also mention crash, could you send an accelerator crash link.

**Comment by narrs** [comment]
I apologize for my late response and ignorance.
I don't know if this file is right.
[accelerator.log](https://github.com/TF2-DMB/CBaseNPC/files/8008700/accelerator.log)
And the reason I concluded was that I arbitrarily deleted the `CTFGameRules::ApplyOnDamageModifyRules` while looking for the cause and confirmed that it worked.

**Comment by Kenzzer** [comment]
> I arbitrarily deleted the `CTFGameRules::ApplyOnDamageModifyRules`

If you delete anything from the gamedata. CBaseNPC will simply refuse loading. It is wrong to conclude, this is was the reason of your crash.

The accelerator log you linked doesn't have any valid crash IDs. Please, make sure accelerator is installed and loaded on your server, and try to reproduce the crash you got.

**Comment by narrs** [comment]
I mean if you don't delete the signature, the game will crash.
If you delete it, it won't crash, but Boss AI won't work. There is a problem with both sides.

Also confirmed that the accelerator was not loaded on the server and reproduced the crash.
[accelerator.log](https://github.com/TF2-DMB/CBaseNPC/files/8008811/accelerator.log)

**Comment by Kenzzer** [comment]
You misunderstand what I'm saying.

Because you deleted `CTFGameRules::ApplyOnDamageModifyRules` from the gamedata. CBaseNPC didn't load, which in turn, means your server didn't crash, because the extension wasn't loaded. But it doesn't mean, that crash is due to `CTFGameRules::ApplyOnDamageModifyRules` signature, it could be something else.

Thank you for that crash ID, we will check it out.

**Comment by Kenzzer** [comment]
Due to a lack of foresight on my part, I must make this second comment.
Could you share the content present on this page, after login in your accelerator account.
https://crash.limetech.org/3atjjimoh7ku/carburetor
If you could also share the CBaseNPC release number you're using too, those information are necessary for us to investigate the crash.

**Comment by narrs** [comment]
https://crash.limetech.org/v2ulf4dwmvha

CBaseNPC release number is 1.2.1.81.

**Comment by Kenzzer** [comment]
Thank you for the release number. Though again we need the information displayed on
https://crash.limetech.org/v2ulf4dwmvha/carburetor
not
https://crash.limetech.org/v2ulf4dwmvha

Only the owner of the crash dump, i.e you, can see that information.

**Comment by KitRifty** [comment]
The latest CBaseNPC release number is 1.3.0.83. Try using the latest release, which you can find here: https://github.com/TF2-DMB/CBaseNPC/releases/tag/1.3.0.83

Since you mentioned that you're using Slender Fortress, I've been running SF2 Modified + the latest CBaseNPC in isolation on a Windows server, and I have not encountered any issues or crashes that you mentioned. Please make sure that gamedata of SF2 and any other plugins you're running are up to date.

**Comment by narrs** [comment]
I used the latest version, but the same bug occurred. 
Also, how can i share the content?

**Comment by Kenzzer** [comment]
Log in your account at https://crash.limetech.org/ then navigate to https://crash.limetech.org/v2ulf4dwmvha/carburetor and then either copy the text there, or share a screenshot of the entire page.

**Comment by narrs** [comment]
[Stack.txt](https://github.com/TF2-DMB/CBaseNPC/files/8010513/Stack.txt)
[Memory.txt](https://github.com/TF2-DMB/CBaseNPC/files/8010515/Memory.txt)
[Raw.txt](https://github.com/TF2-DMB/CBaseNPC/files/8010516/Raw.txt)

**Comment by Kenzzer** [comment]
With the information you provided, we have been unable to reproduce the issue you're reporting, and therefore cannot conclude whether it is really an error on the extension part or not.

Please, work with the gamemode author and provide us a small simple test plugin of your own, where the issue can easily be reproduced.
